<?php

namespace KL\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CmsImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsImageRepository extends EntityRepository
{
}
